myplanner/urls.py
from django.urls import path
from . import views
app_name = "myplanner"
urlpatterns = [
    path('', views.index_view, name="index"),
    path('addtask/', views.add_task, name="add_task"),
    path('add_to_completed/', views.add_to_completed, name='add_to_completed'),
    path('login/', views.auth_view, name="auth"),
    path('logout/', views.logout_view, name="logout"),
    path('sign_up/',views.sign_up_view, name='sign_up')

]

studyplanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myplanner.urls'))
]

myplanner/models.py
from django.db import models
from django.contrib.auth.models import User


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    task_name = models.CharField(max_length=100)
    completed = models.BooleanField(default=0)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.task_name


class Quote(models.Model):
    quote_text = models.CharField(max_length=500)
    author = models.CharField(default="annonymous", max_length=250)

    def __str__(self):
        return self.quote_text + '--' + self.author + '--'

myplanner/forms.py
from django import forms


class LoginForm(forms.Form):
    Email_or_Username = forms.CharField(label="Username", widget=forms.TextInput(attrs={'id': 'sign-in-email'
                                                                                                       '-username'}),
                                        max_length=125)
    password = forms.CharField(widget=forms.PasswordInput(attrs={'id': 'sign-in-password'}))


class SignupForm(forms.Form):
    Email = forms.CharField(label="Email", widget=forms.EmailInput(attrs={'id': 'sign-up-email'}),
                            max_length=125)
    Username = forms.CharField(label="Username", widget=forms.TextInput(attrs={'id': 'username'}))
    Password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'id': 'sign-up-password'}))


class TaskToAddForm(forms.Form):
    task_to_add = forms.CharField(widget=forms.TextInput(attrs={'name': 'task_to_add', 'placeholder':
                                  'type the task you want to add'}), max_length=255)

myplanner/views.py
from django.shortcuts import render, HttpResponseRedirect, reverse
from .models import Task, Quote
import datetime
import random
from .forms import LoginForm, SignupForm, TaskToAddForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from . import custom_form_validations as cfv


def index_view(request):
    if request.user.is_authenticated:
        logged_in = True
        all_tasks = request.user.task_set.filter(date=datetime.date.today()).order_by('-id')
        task_history = request.user.task_set.order_by('-date')
        completed_tasks = request.user.task_set.filter(completed=1, date=datetime.date.today()).order_by('-id')
        uncompleted_tasks = request.user.task_set.filter(completed=0, date=datetime.date.today()).order_by('-id')
        username = request.user.username
    else:
        logged_in = False
        all_tasks = []
        task_history = []
        completed_tasks = []
        uncompleted_tasks = []
        username = ''
    def getquote():
        random_quote_id = random.randint(1, len(Quote.objects.all()))
        try:
            Quote.objects.get(id=random_quote_id)
        except Quote.DoesNotExist:
            getquote()
        else:
            quote = Quote.objects.get(id=random_quote_id)
            return quote
    
    quote = getquote()
    form = TaskToAddForm()
    context = {
        'all_tasks': all_tasks,
        'completed_tasks': completed_tasks,
        'uncompleted_tasks': uncompleted_tasks,
        'task_history': task_history,
        'quote': quote,
        'form': form,
        'logged_in': logged_in,
        'username': username,
    }
    return render(request, 'myplanner/index.html', context)


def add_task(request):
    form = TaskToAddForm(request.POST)
    if form.is_valid():
        task_name = form.cleaned_data['task_to_add']
    if task_name:
        if request.user.is_authenticated:
            new_task = Task(user=request.user, task_name=task_name)
            new_task.save()
            return HttpResponseRedirect(reverse('myplanner:index'))
        else:
            return HttpResponseRedirect(reverse('myplanner:index'))
    else:
        return HttpResponseRedirect(reverse('myplanner:index'))


def add_to_completed(request):
    try:
        task = Task.objects.get(id=request.POST['task'])

    except(KeyError, Task.DoesNotExist):

        return HttpResponseRedirect(reverse('myplanner:index'))

    else:
        if "add_to_completed" in request.POST:
            task.completed = 1
            task.save()
        elif "delete_task" in request.POST:
            task.delete()
        return HttpResponseRedirect(reverse('myplanner:index'))


def auth_view(request):
    login_error_message = ''
    if request.method == "POST":
        if "submit-sign-in-form" in request.POST:
            sign_in_form = LoginForm(request.POST)
            if sign_in_form.is_valid():
                username = sign_in_form.cleaned_data['Email_or_Username']
                password = sign_in_form.cleaned_data['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect(reverse('myplanner:index'))
                else:
                    sign_in_email_or_username_error_message = ''
                    sign_in_password_error_message= ''
                    login_error_message = 'Username and password do not match'
                    if not cfv.validate_username(username)[0]:
                        sign_in_email_or_username_error_message = cfv.validate_username(username)[-1]
                        login_error_message = ''
                    if not cfv.validate_password(password)[0]:
                        sign_in_password_error_message = cfv.validate_password(password)[-1]
                        login_error_message = ''
                    sign_in_form = LoginForm(request.POST)
                    sign_up_form = SignupForm()
                    context = {
                                'sign_in_form': sign_in_form,
                                'sign_up_form': sign_up_form,
                                'login_error_message':login_error_message,
                                'sign_in_email_or_username_error_message':sign_in_email_or_username_error_message,
                                'sign_in_password_error_message':sign_in_password_error_message,
                              }
                    return render(request, 'myplanner/auth.html', context)

        elif "submit-sign-up-form" in request.POST:
            sign_up_form = SignupForm(request.POST)
            if sign_up_form.is_valid():
                username = sign_up_form.cleaned_data['Username']
                email = sign_up_form.cleaned_data['Email']
                password = sign_up_form.cleaned_data['Password']
                try:
                    User.objects.get(username=username)
                except User.DoesNotExist:
                    if cfv.validate_username(username)[0] and cfv.validate_email(email) and cfv.validate_password(password)[0]:
                        User.objects.create_user(username=username, email=email, password=password)
                        new_user = authenticate(username=username, password=password)
                        login(request, new_user)
                        return HttpResponseRedirect(reverse('myplanner:index'))
                    else:
                        sign_up_email_error_message = ''
                        sign_up_password_error_message= ''
                        sign_up_username_error_message= ''
                        if not cfv.validate_email(email):
                            sign_up_email_error_message = "invalid email address"
                        if not cfv.validate_password(password)[0]:
                            sign_up_password_error_message = cfv.validate_password(password)[-1]
                        if not cfv.validate_username(username)[0]:
                            sign_up_username_error_message = cfv.validate_username(username)[-1]
                        sign_in_form = LoginForm()
                        sign_up_form = SignupForm(request.POST)
                        context = {
                                'sign_in_form': sign_in_form,
                                'sign_up_form': sign_up_form,
                                'sign_up_email_error_message':sign_up_email_error_message,
                                'sign_up_password_error_message':sign_up_password_error_message,
                                'sign_up_username_error_message':sign_up_username_error_message,
                              }
                        return render(request, 'myplanner/signup.html', context)


                else:
                    sign_up_username_error_message = 'username is already taken'
                    sign_in_form = LoginForm()
                    sign_up_form = SignupForm(request.POST)
                    context = {
                                'sign_in_form': sign_in_form,
                                'sign_up_form': sign_up_form,
                                'sign_up_username_error_message':sign_up_username_error_message
                              }
                    return render(request, 'myplanner/signup.html', context)
    else:
        sign_in_form = LoginForm()
        sign_up_form = SignupForm()
        context = {
            'sign_in_form': sign_in_form,
            'sign_up_form': sign_up_form,
            'login_error_message':login_error_message
        }
        return render(request, 'myplanner/auth.html', context)


def sign_up_view(request):
    login_error_message = ''
    if request.method == "POST":
        if "submit-sign-in-form" in request.POST:
            sign_in_form = LoginForm(request.POST)
            if sign_in_form.is_valid():
                username = sign_in_form.cleaned_data['Email_or_Username']
                password = sign_in_form.cleaned_data['password']
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    return HttpResponseRedirect(reverse('myplanner:index'))
                else:
                    login_error_message = 'Username and password do not match'
                    sign_in_email_or_username_error_message = ''
                    sign_in_password_error_message= ''
                    login_error_message = 'Username and password do not match'
                    if not cfv.validate_username(username)[0]:
                        sign_in_email_or_username_error_message = cfv.validate_username(username)[-1]
                        login_error_message = ''
                    if not cfv.validate_password(password)[0]:
                        sign_in_password_error_message = cfv.validate_password(password)[-1]
                        login_error_message = ''
                    sign_in_form = LoginForm(request.POST)
                    sign_up_form = SignupForm()
                    context = {
                                'sign_in_form': sign_in_form,
                                'sign_up_form': sign_up_form,
                                'login_error_message':login_error_message
                              }
                    return render(request, 'myplanner/auth.html', context)

        elif "submit-sign-up-form" in request.POST:
            sign_up_form = SignupForm(request.POST)
            if sign_up_form.is_valid():
                username = sign_up_form.cleaned_data['Username']
                email = sign_up_form.cleaned_data['Email']
                password = sign_up_form.cleaned_data['Password']
                try:
                    User.objects.get(username=username)
                except User.DoesNotExist:

myplanner/templates/myplanner/auth.html
{% extends 'base.html' %}
{% block title %}Sign in | Sign up {% endblock title %}
{% block main_content %}

<div class="signin-signup main">
        <div class="form-chosen">
          <button id="sign-in-show-button">sign in</button>
          <button id="sign-up-show-button">sign up</button>
        </div>
        <div class="main-form">
          <form method="POST" id="sign-in-form">
              <h2 style="text-align:center; padding:0;">Sign in</h2>
              {% csrf_token %}
              <div class='error-list'> {% if login_error_message%}{{login_error_message}} {% endif %}</div>

            <div class='form-row'>
            <label for="{{sign_in_form.Email_or_Username.id_for_label}}">{{sign_in_form.Email_or_Username.label}}</label>
            {{sign_in_form.Email_or_Username}}
              <div class='error-list' id='sign_in_email_or_username_error'>
              {% if sign_in_email_or_username_error_message %} {{sign_in_email_or_username_error_message}} {% endif %}
              </div>
            </div>
             
             <div class='form-row'>
            <label for="{{sign_in_form.password.id_for_label}}">{{sign_in_form.password.label}}</label>
                     {{sign_in_form.password}}
              <div class='error-list' id='sign_in_password_error'>
              {% if sign_in_password_error_message %} {{sign_in_password_error_message}} {% endif %}
              </div>
            </div>

            <div class="form-row">
              <input
                type="submit"
                name="submit-sign-in-form"
                id="submit-sign-in-form"
                value="Sign in"
              />
            </div>
          </form>

          <form method="POST" id="sign-up-form">
           <h2 style="text-align:center; padding:0;">Sign up</h2>
              {% csrf_token %}

           <div class='form-row'>
            <label for="{{sign_up_form.Email.id_for_label}}">{{sign_up_form.Email.label}}</label>
            {{sign_up_form.Email}}
              <div class='error-list' id='sign_up_email_error'>
              {% if sign_up_email_error_message %} {{sign_up_email_error_message}} {% endif %}
              </div>
            </div>
             
             <div class='form-row'>
            <label for="{{sign_up_form.Username.id_for_label}}">
             {{sign_up_form.Username.label}}
              </label>
                     {{sign_up_form.Username}}
              <div class='error-list' id='sign_up_username_error'>
              {% if sign_up_username_error_message %} {{sign_up_username_error_message}} {% endif %}
              </div>
            </div>

           <div class='form-row'>
            <label for="{{sign_up_form.Password.id_for_label}}">{{sign_up_form.Password.label}}</label>
                     {{sign_up_form.Password}}
              <div class='error-list' id='sign_up_password_error'>
              {% if sign_up_password_error_message %} {{sign_up_password_error_message}} {% endif %}
              </div>
            </div>


            <div class="form-row">
              <input
                type="submit"
                name="submit-sign-up-form"
                id="submit-sign-up-form"
                value="Sign up"
              />
            </div>
          </form>

        </div>
      </div>
      {% endblock main_content %}

myplanner/templates/myplanner/index.html
{% extends 'base.html' %}
{% block title %}mydayscheduler | Home {% endblock title %}
{% block login %} {% if logged_in %}<div class="login-top-nav"><a href="{% url 'myplanner:logout' %}">Logout</a></div> {% else %}
<div class="login-top-nav"><a href="{% url 'myplanner:auth' %}">Sign in</a></div>
{% endif %}{% endblock login %}
{% block  main_content %}
{% for task in all_real %}
{{task.task_name}}
{% endfor %}
<div class="main">
        <div id="top-of-main"><div style="float:left; padding:0.5rem">{{username|title}}</div> <div id="date"></div></div>
        <!-- quotes section -->
        <div id="quote">
          <p>
            {{quote.quote_text}}-{{quote.author}}
          </p>
        </div>
        <!-- end of quotes -->
        <div id="tasks-weather-header">
          <button id="task-button">My tasks</button>
          <button id="weather-button">My weather</button>
        </div>
        <div id="tasks-weather">
          <div class="weather-info">
            <div id="weather-form">
              <input
                type="text"
                name="weather"
                placeholder="type in your city"
                id="city"
              />
              <button id="get-weather">get weather</button>
            </div>
            <div id="my-weather">
              <h3 id="weather-heading"></h3>
              <p id="temperature"></p>
              <p id="humidity"></p>
              <p id="pressure"></p>
              <p id="min-temp"></p>
              <p id="max-temp"></p>
            </div>
          </div>

          <div class="task-info">
            <div id="submit-task-form">
              <form
                action="{% url 'myplanner:add_task' %}"
                method="post"
                enctype="multipart/form-data"
              >
                {% csrf_token %}
                {{form.task_to_add}}
                <button>add task</button>
              </form>
            </div>
            {% if error_message %} {{error_message}} {% endif %}
            <div class="my-tasks">
              <div class="task-types">
                <button id="all-tasks-button">Todays tasks</button>
                <button id="completed-tasks-button">completed tasks</button>
                <button id="uncompleted-tasks-button">
                  uncompleted tasks
                </button>
                <button id="tasks-history-button">
                  Task History
                </button>
              </div>
              <form
                method="POST"
                action="{% url 'myplanner:add_to_completed' %}"
              >
                {% csrf_token %}
                <div class="all-tasks">
                  {% if all_tasks %}
                  <div class="ayholder">
                    <div
                      class="all-tasks-first-child"
                      style="text-align: center;border-top: 1px solid #000;"
                    >
                      Task
                    </div>
                    <div
                      class="all-tasks-second-child"
                      style="justify-content: center;border-top: 1px solid #000;"
                    >
                      Completed
                    </div>
                  </div>
                  {% for task in all_tasks %}
                  <div class="ayholder">
                    <div class="all-tasks-first-child">
                      <input type="radio" value="{{task.id}}" name="task" />
                      {{task.task_name}}
                    </div>
                    <div class="all-tasks-second-child">
                      {% if task.completed %}
                      <i class="fas fa-check"></i>
                      {% else %}
                      <i class="fas fa-times" style="color:red"></i>
                      {% endif %}
                    </div>
                  </div>
                  {% endfor %} {% else %}
                  {% if logged_in %}
                  <p>oops no tasks in the database</p>
                  {% else %}
                  <p>Please <a style="color:rgb(60, 230, 130);" href="{% url 'myplanner:auth' %}">Sign in</a> to view your tasks</p>
                  {% endif %}
                  
                  {% endif %}
                </div>
                <!-- end of all tasks -->
                {% if all_tasks %}
                <input
                  name="delete_task"
                  type="submit"
                  id="delete-button"
                  value="Delete task"
                />
                <input
                  name="add_to_completed"
                  type="submit"
                  id="completed-button"
                  value="Add to completed"
                />
                {% endif %}
              </form>

              <div class="completed-tasks">
                {% if completed_tasks%}
                <div class="ayholder">
                  <div
                    class="all-tasks-first-child"
                    style="text-align: center;"
                  >
                    Task
                  </div>
                  <div
                    class="all-tasks-second-child"
                    style="justify-content: center;"
                  >
                    Completed
                  </div>
                </div>
                {% for task in completed_tasks%}
                <div class="ayholder">
                  <div class="all-tasks-first-child">
                    {{task.task_name}}
                  </div>
                  <div class="all-tasks-second-child">
                    <i class="fas fa-check"></i>
                  </div>
                </div>
                {% endfor %} {% else %}
                {% if logged_in %}
                  <p>No completed tasks</p>
                  {% else %}
                  <p>Please <a style="color:rgb(60, 230, 130);" href="{% url 'myplanner:auth' %}">Sign in</a> to view your tasks</p>
                  {% endif %}
                {% endif %}
              </div>

              <div class="uncompleted-tasks">
                {% if uncompleted_tasks %}
                <div class="ayholder">
                  <div
                    class="all-tasks-first-child"
                    style="text-align: center;"
                  >
                    Task
                  </div>
                  <div
                    class="all-tasks-second-child"
                    style="justify-content: center;"
                  >
                    Completed
                  </div>
                </div>

                {% for task in uncompleted_tasks %}
                <div class="ayholder">
                  <div class="all-tasks-first-child">
                    {{task.task_name}}
                  </div>
                  <div class="all-tasks-second-child">
                    <i class="fas fa-times" style="color: red;"></i>
                  </div>
                </div>
                {% endfor %} {% else %}
                {% if logged_in %}
                  <p>No uncompleted tasks</p>
                  {% else %}
                  <p>Please <a style="color:rgb(60, 230, 130);" href="{% url 'myplanner:auth' %}">Sign in</a> to view your tasks</p>
                  {% endif %}
                {% endif %}
              </div>

              <div class="task-history">
                {% if task_history %}
                <div class="ayholder">
                  <div
                    class="all-tasks-first-child"
                    style="text-align: center;"
                  >
                    Task
                  </div>
                  <div
                    class="all-tasks-second-child"
                    style="justify-content: center;"
                  >
                    Completed
                  </div>
                </div>

                {% for task in task_history %}
                <div class="ayholder">
                  <div class="all-tasks-first-child">
                    {{task.task_name}}
                  </div>
                  <div class="all-tasks-second-child">
                    {% if task.completed %}
                    <i class="fas fa-check"></i>
                    {% else %}
                    <i class="fas fa-times" style="color:red"></i>
                    {% endif %}
                  </div>
                </div>
                {% endfor %} {% else %}
                {% if logged_in %}
                  <p>oops no tasks in the database</p>
                  {% else %}
                  <p>Please <a style="color:rgb(60, 230, 130);" href="{% url 'myplanner:auth' %}">Sign in</a> to view your tasks</p>
                  {% endif %}
                {% endif %}
              </div>
              <!-- end of task history -->
            </div>
          </div>
          <!-- end of task info -->
        </div>
      </div>
{% endblock main_content %}

myplanner/templates/myplanner/signup.html
{% extends 'base.html' %} {% block title %}Sign in | Sign up {% endblock title%} {% block main_content %}

<div class="signin-signup main">
  <div class="form-chosen">
    <button id="sign-in-show-button">sign in</button>
    <button id="sign-up-show-button">sign up</button>
  </div>
  <div class="main-form">
    <form method="POST" id="sign-in-form" style="display:none">
      <h2 style="text-align:center; padding:0;">Sign in</h2>
      {% csrf_token %}
      <div class="error-list">
        {% if login_error_message%}{{login_error_message}} {% endif %}
      </div>

        <div class='form-row'>
            <label for="{{sign_in_form.Email_or_Username.id_for_label}}">{{sign_in_form.Email_or_Username.label}}</label>
            {{sign_in_form.Email_or_Username}}
              <div class='error-list' id='sign_in_email_or_username_error'></div>
            </div>
             
             <div class='form-row'>
            <label for="{{sign_in_form.password.id_for_label}}">{{sign_in_form.password.label}}</label>
                     {{sign_in_form.password}}
              <div class='error-list' id='sign_in_password_error'></div>
            </div>

      <div class="form-row">
        <input
          type="submit"
          name="submit-sign-in-form"
          id="submit-sign-in-form"
          value="Sign in"
        />
      </div>
    </form>

    <form method="POST" id="sign-up-form" style="display:block">
      <h2 style="text-align:center; padding:0;">Sign up</h2>
      <div class='error-list'>{% if sign_up_error_message %} {{sign_up_error_message}} {% endif %}</div>
      {% csrf_token %} 
      
       <div class='form-row'>
            <label for="{{sign_up_form.Email.id_for_label}}">{{sign_up_form.Email.label}}</label>
            {{sign_up_form.Email}}
              <div class='error-list' id='sign_up_email_error'>
              {% if sign_up_email_error_message %} {{sign_up_email_error_message}} {% endif %}
              </div>
            </div>
             
             <div class='form-row'>
            <label for="{{sign_up_form.Username.id_for_label}}">
             {{sign_up_form.Username.label}}
              </label>
                     {{sign_up_form.Username}}
              <div class='error-list' id='sign_up_username_error'>
              {% if sign_up_username_error_message %} {{sign_up_username_error_message}} {% endif %}
              </div>
            </div>

           <div class='form-row'>
            <label for="{{sign_up_form.Password.id_for_label}}">{{sign_up_form.Password.label}}</label>
                     {{sign_up_form.Password}}
              <div class='error-list' id='sign_up_password_error'>
              {% if sign_up_password_error_message %} {{sign_up_password_error_message}} {% endif %}
              </div>
            </div>

      <div class="form-row">
        <input
          type="submit"
          name="submit-sign-up-form"
          id="submit-sign-up-form"
          value="Sign up"
        />
      </div>
    </form>
  </div>
</div>
{% endblock main_content %}